pub(crate) enum AppCommand {
    TopbarSpeed(hoi4_ui::topbar::SpeedCommand),
    SideRailPanel(hoi4_ui::PanelKind),
    Panel(hoi4_ui::PanelCommand),
    CloseActivePanel,
    FinishPoliticsClose,
    CloseLawPanel,
    CloseConstructionPanel,
    Finance(hoi4_ui::finance_panel::FinanceCommand),
    ConstructionV6(hoi4_ui::construction_v6_panel::ConstructionV6Command),
    Law(hoi4_ui::law_panel::LawCommand),
    Decision(hoi4_ui::politics::DecisionCommand),
    Research(hoi4_ui::research::ResearchCommand),
    Diplomacy(hoi4_ui::diplomacy::DiplomacyCommand),
    Military(hoi4_ui::military::MilitaryCommand),
    Air(hoi4_ui::air::AirCommand),
    Naval(hoi4_ui::naval::NavalCommand),
    Situation(hoi4_ui::situation_panel::SituationCommand),
    Focus(hoi4_ui::focus_tree_panel::FocusCommand),
    CountryInfo(hoi4_ui::country_info_panel::CountryInfoCommand),
    CounterMenu(&'static str),
    Event(hoi4_ui::event_panel::EventCommand),
    SurrenderNotification(hoi4_ui::surrender_notification::SurrenderNotificationCommand),
    Settings(hoi4_ui::settings::SettingsCommand),
    Save(hoi4_ui::save_browser::SaveCommand),
    End(hoi4_ui::end_screen::EndCommand),
}
