[package]
name = "clausewitz-parser"
version = "0.1.0"
edition = "2021"
license.workspace = true

[features]
default = []
vanilla-audit = []

[dev-dependencies]
hoi4-paths = { path = "../hoi4-paths" }

[[test]]
name = "integration"
path = "tests/integration.rs"
required-features = ["vanilla-audit"]
